services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./src:/var/www/laravel
        depends_on:
#            - mysql
            - pgsql
            - php
        networks:
            - laravel

    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel
        networks:
            - laravel

#    redis:
#        image: redis
#        ports:
#            - "6378:6379"
#        env_file:
#            - env/redis.env
#        volumes:
#            - db_data:/data
#        networks:
#            - laravel

#    mysql:
#        image: mysql:8.0
#        ports:
#            - "3316:3306"
#        env_file:
#            - env/mysql.env
#        volumes:
#            - db_data:/var/lib/mysql
#        networks:
#            - laravel

    pgsql:
        image: 'postgres:latest'
        ports:
            - "5431:5432"
        env_file:
            - env/pgsql.env
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - laravel

    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - ./src:/var/www/laravel
        networks:
            - laravel

    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - ./src:/var/www/laravel
        entrypoint: [ "php", "/var/www/laravel/artisan" ]
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
volumes:
    db_data:

